[tool.black]
line-length = 120
target-version = ['py311']
skip-string-normalization = true
skip-numeric-underscore-normalization=true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.env
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | node_modules
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip = '.venv,.env,.git,node_modules,migrations,dist,build'
known_first_party = ''
